#!/usr/bin/env ruby
#echo = "echo "
echo=""

  system("#{echo} heroku config:add BUNDLE_WITHOUT=development:test:cucumber")
  system("#{echo} heroku addons:add sendgrid:starter")
  system("#{echo} heroku addons:add logging:basic")
  system("#{echo} heroku addons:add newrelic:standard")
  system("#{echo} heroku addons:add ssl:piggyback")
  system("#{echo} heroku addons:add shared-database:5mb")
  system("#{echo} " + %q[ruby -ne 'if /export (.*=.*)/; f=$1; puts f; %x(heroku config:add #{f}); end' .powenv])
  puts "ready for code push.."
