#!/usr/bin/env ruby
def app
  app_name = ENV['app'] || ENV['app'] || ARGV.first
  raise "Please specify a APP=(name)" unless app_name
  app_name
end

#echo = "echo "
echo=""

system("#{echo} heroku create #{app} --stack bamboo-mri-1.9.2")
system("#{echo} heroku config:add BUNDLE_WITHOUT=development:test:cucumber")
system("#{echo} heroku addons:add exceptional:basic")
system("#{echo} heroku addons:add newrelic:bronze")
system("#{echo} heroku addons:add ssl:piggyback")
puts "ready for code push.."
