development:
  adapter: postgresql
  encoding: unicode
  database: haidb_development
  pool: 5
  username:
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: haidb_test
  pool: 5
  username:
  password:
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: haidb_development
  pool: 5
  username:
  password:
  host: localhost
  port: 5432
